arrowParens: "always"
bracketSameLine: false
bracketSpacing: true
embeddedLanguageFormatting: "auto"
htmlWhitespaceSensitivity: "css"
insertPragma: false
jsxSingleQuote: true
proseWrap: "preserve"
quoteProps: "as-needed"
requirePragma: false
semi: true
singleQuote: true
tabWidth: 2
trailingComma: "none"
useTabs: true
vueIndentScriptAndStyle: false
printWidth: 120
endOfLine: "lf"
